/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view;

import controller.TabuleiroController;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Ponto;
import observer.IObserver;

/**
 *
 * @author davif
 */
public class ViewGame extends javax.swing.JFrame implements IObserver {

    private JButton[][] botoes;
    private TabuleiroController tabuleiroController;
    private Ponto pontoSelecionadoOrigem;
    private Ponto pontoSelecionadoDestino;
    private JPanel tabuleiroPainel;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewGame.class.getName());

    /**
     * Creates new form ViewGame
     */
    public ViewGame(TabuleiroController tabuleiroController) {
        this.tabuleiroController = tabuleiroController;
        this.tabuleiroController.addListener(this);
        this.tabuleiroPainel = new JPanel(new GridLayout(7, 7));
        
        setTitle("Resta Um");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());
        
        this.tabuleiroController.iniciarJogo();
        
        JButton reiniciar = new JButton("Reiniciar");
        reiniciar.addActionListener(e -> tabuleiroController.iniciarJogo());
        add(reiniciar, BorderLayout.SOUTH);
        
        pack();
        setLocationRelativeTo(null);
        setVisible(true);

        initComponents();
    }

    public void notificaInicioJogo(){
        this.recarregarPainelTabuleiro();

        add(tabuleiroPainel, BorderLayout.CENTER);
    }
    
    public void onBuildTabuleiro(JPanel tabuleiroPanel){
        botoes = new JButton[7][7];
        
        for (int i = 0; i < 7; i++) {
            for (int j = 0; j < 7; j++) {
                JButton btn = new JButton();
                btn.setPreferredSize(new Dimension(50, 50));
                btn.setBackground(Color.RED);
                btn.setBorder(BorderFactory.createLineBorder(Color.BLACK));

                if (tabuleiroController.getPosicao(new Ponto(i, j)) == 0) {
                    btn.setBackground(Color.WHITE);
                }
                
                final int x = i;
                final int y = j;
                
                btn.addMouseListener((new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        tabuleiroController.botaoClick(x, y);
                    }
                }));

                btn.setFont(new Font("SansSerif", Font.BOLD, 24));

                botoes[i][j] = btn;

                if (tabuleiroController.isPosicaoInvalida(new Ponto(i, j))) {
                    btn.setBackground(Color.GRAY);
                    btn.setBorder(BorderFactory.createLineBorder(Color.WHITE));
                    btn.setEnabled(false);
                }

                tabuleiroPanel.add(btn);
            }
        }
    }
    
    public void marcaBotao(Ponto ponto){
        botoes[ponto.getX()][ponto.getY()].setBackground(new Color(138, 21, 21));
    }
    
    public void desmarcaBotao(Ponto ponto){
        botoes[ponto.getX()][ponto.getY()].setBackground(Color.RED);
    }
    
    public void notificaCancelarJogada(Ponto ponto){
        this.desmarcaBotao(ponto);
    }
    
    public void notificaSelecionarBotao(Ponto ponto){
        this.marcaBotao(ponto);
    }
    
    public void notificaFinalizarJogada(){
        this.recarregarPainelTabuleiro();
    }
    
    public void notificaVitoriaJogo(){
        this.recarregarPainelTabuleiro();
        JOptionPane.showMessageDialog(rootPane, "Parabéns, você ganhou!");
    }
    
    public void notificaDerrotaJogo(){
        this.recarregarPainelTabuleiro();
        JOptionPane.showMessageDialog(rootPane, "Você perdeu!");
    }
    
    private void recarregarPainelTabuleiro() {
        this.resetPainel();
        this.onBuildTabuleiro(this.tabuleiroPainel);
    }
    
    public void resetPainel(){
        this.tabuleiroPainel.removeAll();
        this.tabuleiroPainel.revalidate();
        this.tabuleiroPainel.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewGame(new TabuleiroController()).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
